### PR TITLE
Extend the API with 'observeVerificationRequests' and an additional parameter

### PR DESCRIPTION
**Pull request by n9iels**
## Description
This PR add the `observeVerificationRequests` method to the API. This makes the implementation of connectors that require additional verification before a claim can be verified possible. An example of such a connector is [IPv8 connector](https://github.com/discipl/discipl-core-ipv8/)

Another change in this PR is an additional parameter for the `claim` method. This parameter, named `attester`, makes it possible to express the did of the expected attester. This makes it possible to implement a connector that requires both parties to be known when creating a claim.

## Backwards compatibility
No breaking changes are made in this PR

### CODE REVIEW

**Review by pimotte — CHANGES_REQUESTED** [review]
One tiny documentation request.

Other than that, LGTM.

For most of the ephemeral functionality we actually have integration tests. How would you feel about having an integration-test for ipv8 in core? This would serve as an example how to use this method as well. If we would do this, I would split it off in a separate file and just run through a common scenario involving verification of a claim. A reason not to do it would be if it's very flaky or needs a LOT of machinery to work.

**Comment by n9iels** [comment]
Adding integration tests is possible since there is already a implementation for this in the [discipl-core-ipv8 repo itself](https://github.com/discipl/discipl-core-ipv8/tree/master/test/integration/ipv8).

I do need to say that the integration tests currently are not stable. Sometimes they randomly fail and after a restart they pass without any problems. I will take a look at that issue first (https://github.com/discipl/discipl-core-ipv8/issues/15), after that I will implement it here.

**Comment by n9iels** [comment]
@pimotte I added some integration tests for the IPv8 connector. Once the npm package is live Travis should be happy too :smile:

**Review by pimotte — APPROVED** [review]
:tada:

**Pull request merged**
