### PR TITLE
Adding code coverage

### PR DESCRIPTION
**Pull request by pimotte**
Based on #16 

Does actually not include karma, because it I couldn't get it to work, and if we can get coverage without it, I'm not sure why we would need it.

### CODE REVIEW

**Comment by pimotte** [comment]
Also including codecov may be overkill, as sonar can also track code coverage. This does give allow showing codecoverage before merging.

**Comment by bkaptijn** [comment]
If we can use  for code coverage even before merge than better use that than yet another tool like karma.

I invitef you to be member of discipl dev github team earlier this week .. are you not able to create your own dev branch? should be possible for you to make internal PR's

**Comment by bkaptijn** [comment]
But let us try using codecov for now too

**Comment by pimotte** [comment]
> If we can use for code coverage even before merge than better use that than yet another tool like karma.
> 
> I invitef you to be member of discipl dev github team earlier this week .. are you not able to create your own dev branch? should be possible for you to make internal PR's

@bkaptijn Nope. My guess is that you would want to add the repository here https://github.com/orgs/discipl/teams/discipl-dev/repositories with "write" rights, or add the team here https://github.com/discipl/core/settings/collaboration

**Comment by bkaptijn** [comment]
Ah ok, sorry, added repos with write access to the team but i now see steven used the team for non devs too.. will create a better team structure later today

**Pull request merged**
